### ISSUE TITLE
step 3 meet followed issue

### ISSUE THREAD

**Issue by lcgogo** [hashicorp/learn-terraform-import#8]
```console
root@ip-192-168-0-59:~/learn-terraform-import# terraform import docker_container.web $(docker inspect -f {{.ID}} hashicorp-learn)
╷
│ Error: Error initializing Docker client: protocol not available
│
│   with provider["registry.terraform.io/kreuzwerker/docker"],
│   on /root/learn-terraform-import/main.tf line 14, in provider "docker":
│   14: provider "docker" {
│
╵

root@ip-192-168-0-59:~/learn-terraform-import# docker --version
Docker version 20.10.8, build 3967b7d
root@ip-192-168-0-59:~/learn-terraform-import# terraform --version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/kreuzwerker/docker v2.11.0

Your version of Terraform is out of date! The latest version
is 1.0.8. You can update by downloading from https://www.terraform.io/downloads.html
root@ip-192-168-0-59:~/learn-terraform-import#

```

**Comment by abarberenaCPDS** [comment]
#### Update 👋 

Following this tutorial on Mar/2022, I found these issues:

- 1 . 🔴 Error: Error initializing Docker client: protocol not available
  - Symptom: Initializing Terraform failed due the provider configuration in *main.tf*
  - Solution: Follow the [Docker Provider Example usage](https://github.com/kreuzwerker/terraform-provider-docker)
    - **host** can be commented out and still work
    - The version was set to 2.16.0 explicitly
    - **required_version** was commented
``` terraform
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.16.0"
    }
  }
  # required_version = ">= 0.14"
}

provider "docker" {
  # host    = "npipe:////.//pipe//docker_engine"
   host = "unix:///var/run/docker.sock"
}
```

- 2 . 🟠 Broken Link on the provider page 

<img width="945" alt="image" src="https://user-images.githubusercontent.com/43246964/159175331-be71a7a9-94fa-4ee9-a241-912a2509f5c3.png">

**Comment by rkoron007** [comment]
Hello! Apologies for the _very late_ response here, but we've updated this tutorial since this issue was filed, and these updates (plus my own PR) fix the issues described above:
1. The link to the Docker provider docs is now valid.
2. We've updated the docker provider version to `3.0.2` and I'm adding a `.terraform.lock.hcl` file to ensure the version folks download when running this tutorial matches the docker provider version I tested locally (on MacOS).
3. Use `host = "unix:///var/run/docker.sock"` in the docker provider configuration (`main.tf`)

This should fix the issues you raised above, so I'm going to close this issue for now, but **thank you** all so much for raising these problems and helping to make our tutorials better!
